# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '\u53d1\u5e03\u4f1a', 'verbose_name_plural': '\u53d1\u5e03\u4f1a'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': '\u5609\u5bbe', 'verbose_name_plural': '\u5609\u5bbe'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(verbose_name='\u53c2\u52a0\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u53d1\u5e03\u4f1a\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u4f1a\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Event', verbose_name='\u5173\u8054\u53d1\u5e03\u4f1a'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='realname',
            field=models.CharField(max_length=64, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sign',
            field=models.BooleanField(verbose_name='\u7b7e\u5230\u72b6\u6001'),
        ),
    ]
