# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170710_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest1',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faf', to='sign.Event', verbose_name='\u5173\u8054\u53d1\u5e03\u4f1a'),
        ),
    ]
