# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20170710_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest1',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='guest1',
            name='event',
        ),
        migrations.DeleteModel(
            name='Guest1',
        ),
    ]
